"""
02_augment_splatt3r.py  —  Novel view synthesis via Splatt3R (feed-forward Gaussians).

Drop-in alternative to 02_augment.py.  Identical output format.

Key difference:
  Splatt3R predicts 3D Gaussian splats in a single forward pass — no 3DGS
  optimisation loop.  Typically 5–10× faster than 02_augment.py per frame.

How it works:
  1. Splatt3R's encoder (= frozen MASt3R) runs global alignment → camera poses.
  2. Splatt3R's Gaussian heads predict splat parameters (one forward pass).
  3. Novel-view cameras are generated by Slerp-interpolation (same as step 2).
  4. gsplat renders each novel view directly from the predicted splats.

── Setup (run once) ────────────────────────────────────────────────────────────

  git clone https://github.com/btsmart/splatt3r  /opt/splatt3r   # or any path
  cd /opt/splatt3r
  # Install the custom CUDA rasterizer (required):
  pip install git+https://github.com/dcharatan/diff-gaussian-rasterization-modified
  pip install plyfile einops                                       # extra deps

── Usage ────────────────────────────────────────────────────────────────────────

  # Single episode
  python 02_augment_splatt3r.py \\
      --episode_dir data/episodes/hammer/001 \\
      --splatt3r_dir /opt/splatt3r

  # All episodes in a task (model loaded once)
  python 02_augment_splatt3r.py \\
      --task_dir data/episodes/hammer \\
      --splatt3r_dir /opt/splatt3r

── Outputs (identical to 02_augment.py) ────────────────────────────────────────

  augmented/
      real/              ← copies of sampled real frames ({fid}_cam{i}.jpg)
      novel/             ← novel-view JPEG renders ({fid}_novel{k:02d}.jpg)
      novel_cameras.npz  ← per-frame w2c matrices + intrinsics (for step 4)
"""

import os, sys, json, time, shutil, tempfile, argparse
import numpy as np
import torch
import torch.nn.functional as F
import cv2

# NOTE: starster is intentionally NOT imported here.
# It must be imported AFTER Splatt3R is loaded because both Splatt3R and starster
# ship modified versions of `mast3r`; if starster loads first it caches the
# standard mast3r in sys.modules and Splatt3R's modified head fails to load.
# See _get_starster() below for the lazy import.

from pipeline_utils.geometry import generate_novel_view_w2c

MAST3R_SIZE  = 512
PIPELINE_DIR = os.path.dirname(os.path.abspath(__file__))

# HuggingFace repo / filename for the Splatt3R checkpoint
SPLATT3R_HF_REPO = "brandonsmart/splatt3r_v1.0"
SPLATT3R_CKPT    = "epoch=19-step=1200.ckpt"


# ── Lazy starster import ──────────────────────────────────────────────────────

_starster = None

def _get_starster():
    """Return the starster module, importing it on first call.

    Must be called AFTER load_splatt3r() — Splatt3R must populate
    sys.modules['mast3r'] with its modified version before starster loads the
    standard one, otherwise Splatt3R's Gaussian heads fail to instantiate.
    """
    global _starster
    if _starster is None:
        import starster as _s
        _starster = _s
    return _starster


# ── Splatt3R setup ────────────────────────────────────────────────────────────

def setup_splatt3r(splatt3r_dir: str):
    """Add Splatt3R to sys.path and return the MAST3RGaussians class."""
    splatt3r_dir = os.path.abspath(splatt3r_dir)

    # Splatt3R's main.py calls sys.path.append('src/pixelsplat_src') etc.
    # with paths relative to CWD — temporarily chdir so they resolve correctly.
    prev_cwd = os.getcwd()
    try:
        os.chdir(splatt3r_dir)
        for subdir in ['src/pixelsplat_src', 'src/mast3r_src',
                       'src/mast3r_src/dust3r']:
            abs_sub = os.path.join(splatt3r_dir, subdir)
            if abs_sub not in sys.path:
                sys.path.insert(0, abs_sub)
        if splatt3r_dir not in sys.path:
            sys.path.insert(0, splatt3r_dir)
        # Clear any stale utils.* entries from namespace-package caching
        for key in list(sys.modules.keys()):
            if key == 'utils' or key.startswith('utils.'):
                del sys.modules[key]

        # splatt3r/utils/ has no __init__.py so Python treats it as a namespace
        # package and may merge it with croco/utils, later losing to a regular
        # package elsewhere.  Force-load splatt3r's utils as a regular package.
        import types as _types, importlib.util as _ilu
        _utils = _types.ModuleType('utils')
        _utils.__path__ = [os.path.join(splatt3r_dir, 'utils')]
        _utils.__package__ = 'utils'
        sys.modules['utils'] = _utils
        for _name in ['geometry', 'compute_ssim', 'export', 'sh_utils', 'loss_mask']:
            _mod_name = f'utils.{_name}'
            _mod_path = os.path.join(splatt3r_dir, 'utils', f'{_name}.py')
            if os.path.exists(_mod_path):
                _spec = _ilu.spec_from_file_location(_mod_name, _mod_path)
                _mod  = _ilu.module_from_spec(_spec)
                sys.modules[_mod_name] = _mod
                _spec.loader.exec_module(_mod)

        try:
            from main import MAST3RGaussians
            return MAST3RGaussians
        except ImportError as e:
            raise ImportError(
                f"Cannot import MAST3RGaussians from {splatt3r_dir}.\n"
                "  Make sure you have cloned Splatt3R and installed its deps:\n"
                "    pip install git+https://github.com/dcharatan/diff-gaussian-rasterization-modified\n"
                "    pip install plyfile einops lpips\n"
                f"  Original error: {e}"
            )
    finally:
        os.chdir(prev_cwd)


def load_splatt3r(splatt3r_dir: str, device: str) -> "MAST3RGaussians":
    """Load Splatt3R from HuggingFace (downloads checkpoint on first run)."""
    from huggingface_hub import hf_hub_download
    MAST3RGaussians = setup_splatt3r(splatt3r_dir)

    ckpt_path = hf_hub_download(repo_id=SPLATT3R_HF_REPO, filename=SPLATT3R_CKPT)
    print(f"  Checkpoint: {ckpt_path}")
    model = MAST3RGaussians.load_from_checkpoint(ckpt_path, map_location=device)
    model = model.to(device).eval()
    print(f"  Splatt3R loaded on {device}")
    return model


# ── Image preparation ─────────────────────────────────────────────────────────

def to_splatt3r_view(img_tensor: torch.Tensor, device: str, idx: int = 0) -> dict:
    """
    Convert a starster-loaded image to the view dict Splatt3R expects.

    starster.load_image returns a (3, H, W) tensor normalised to [-1, 1].
    Splatt3R additionally needs 'original_img' in [0, 1], plus 'idx' and
    'instance' keys required by dust3r's is_symmetrized() check.
    """
    img = img_tensor.to(device)
    return {
        'img':          img.unsqueeze(0),                     # (1, 3, H, W)  [-1, 1]
        'original_img': ((img + 1.0) / 2.0).unsqueeze(0),    # (1, 3, H, W)  [0, 1]
        'true_shape':   torch.tensor([img.shape[-2:]]),       # (1, 2) = [H, W]
        'idx':          idx,
        'instance':     str(idx),
    }


# ── Gaussian extraction ───────────────────────────────────────────────────────

def extract_gaussians(pred1: dict, pred2: dict, opacity_threshold: float = 0.01,
                      max_gaussians: int = 60_000,
                      device: str = 'cuda') -> dict | None:
    """
    Flatten Splatt3R predictions into arrays ready for gsplat.rasterization.

    Splatt3R outputs Gaussians in VIEW-1 (cam0) camera frame:
      - pred1['means']               : (1, H, W, 3)  — Gaussians from view 1
      - pred2['means_in_other_view'] : (1, H, W, 3)  — Gaussians from view 2,
                                                         already in view-1 frame

    We define cam0 = world origin, so no additional coordinate transform is needed.

    Returns a dict with keys: means, quats, scales, opacities, colors_dc
    or None if all Gaussians are pruned.
    """
    def flat(t):
        return t[0].reshape(-1, t.shape[-1])   # (H*W, C)

    # ── 3D positions ──────────────────────────────────────────────────────────
    means1 = flat(pred1['means'])                    # (H*W, 3)
    means2 = flat(pred2['means_in_other_view'])       # (H*W, 3)
    all_means = torch.cat([means1, means2])

    # ── Rotations (quaternions, assumed w,x,y,z) ──────────────────────────────
    quats1 = flat(pred1['rotations'])                 # (H*W, 4)
    quats2 = flat(pred2['rotations'])
    all_quats = F.normalize(torch.cat([quats1, quats2]), dim=-1)

    # ── Scales ────────────────────────────────────────────────────────────────
    # Splatt3R's head already outputs scales in LINEAR space (build_covariance
    # uses them directly).  Do NOT apply exp() — it would inflate metre-scale
    # values to ~1 m, covering the whole scene.
    scales1 = flat(pred1['scales'])                   # (H*W, 3)
    scales2 = flat(pred2['scales'])
    all_scales = torch.cat([scales1, scales2]).clamp(min=1e-6)

    # ── Opacities ─────────────────────────────────────────────────────────────
    # The Gaussian head applies sigmoid internally; values are already in [0,1].
    ops1 = pred1['opacities'][0].reshape(-1)          # (H*W,)
    ops2 = pred2['opacities'][0].reshape(-1)
    all_opacities = torch.cat([ops1, ops2]).clamp(0.0, 1.0)

    # ── Colors (DC SH → RGB) ──────────────────────────────────────────────────
    # pred['sh'] has shape (1, H, W, 3, K) where [..., 0] = DC SH coefficient.
    # Splatt3R uses standard 3DGS SH convention:
    #   RGB2SH(rgb) = (rgb - 0.5) / C0   (C0 = 0.28209...)
    #   SH2RGB(dc)  = dc * C0 + 0.5
    # We convert to linear RGB here and pass sh_degree=None to gsplat so it
    # uses the values directly (no second SH evaluation).
    _C0 = 0.28209479177387814
    sh1 = pred1['sh'][0]    # (H, W, 3, K)  or  (H, W, K*3)
    sh2 = pred2['sh'][0]

    def dc_to_rgb(sh):
        # Handle both (H, W, 3, K) and (H, W, K*3) layouts.
        if sh.dim() == 4:                           # (H, W, 3, K)
            dc = sh[..., 0]                         # (H, W, 3)
        else:                                       # (H, W, K*3) flattened
            dc = sh.reshape(sh.shape[0], sh.shape[1], -1, 3)[..., 0, :]
        return (dc * _C0 + 0.5).clamp(0.0, 1.0).reshape(-1, 3)  # (H*W, 3)

    colors1 = dc_to_rgb(sh1)
    colors2 = dc_to_rgb(sh2)
    # sh_degree=None → gsplat treats colors as pre-computed RGB, shape (N, 3)
    all_colors = torch.cat([colors1, colors2])

    # ── Opacity-based pruning ─────────────────────────────────────────────────
    if opacity_threshold > 0:
        keep = all_opacities > opacity_threshold
        if keep.sum() >= 100:
            all_means     = all_means[keep]
            all_quats     = all_quats[keep]
            all_scales    = all_scales[keep]
            all_opacities = all_opacities[keep]
            all_colors    = all_colors[keep]

    # ── Cap total Gaussians to avoid GPU OOM during rendering ─────────────────
    N = len(all_means)
    if max_gaussians > 0 and N > max_gaussians:
        idx = torch.randperm(N, device=all_means.device)[:max_gaussians]
        all_means     = all_means[idx]
        all_quats     = all_quats[idx]
        all_scales    = all_scales[idx]
        all_opacities = all_opacities[idx]
        all_colors    = all_colors[idx]

    return dict(
        means=all_means,
        quats=all_quats,
        scales=all_scales,
        opacities=all_opacities,
        colors=all_colors,
    )


# ── Novel-view rendering ──────────────────────────────────────────────────────

def render_novel_views(gaussians: dict, w2c_cam0: torch.Tensor, w2c_cam1: torch.Tensor,
                       K: torch.Tensor, num_novel_views: int, device: str):
    """
    Generate novel-view camera poses via Slerp and render with gsplat.

    Coordinate system:  cam0 = world origin  (cam0_w2c = I).
    cam1_w2c_local  = w2c_cam1 @ inv(w2c_cam0)   (cam1 relative to cam0).
    novel_w2c_local = Slerp(I, cam1_w2c_local).

    Returns:
      renders         — list of (H, W, 3) uint8 RGB arrays
      novel_w2c_np    — (N, 4, 4) float64 novel-view w2c  (in cam0-local frame)
      K_novel_np      — (N, 3, 3) float64 intrinsics
      cam0_w2c_np     — (4, 4) float64 identity
      cam1_w2c_np     — (4, 4) float64 cam1 relative to cam0
    """
    import gsplat

    if num_novel_views % 2 != 0:
        raise ValueError("num_novel_views must be even")

    # Local cam1 w2c: cam1 relative to cam0 (cam0 is world origin)
    c2w_cam0       = torch.inverse(w2c_cam0)              # cam0-to-world (= I for local frame)
    cam1_w2c_local = (w2c_cam1 @ c2w_cam0).to(device)     # (4, 4)
    cam0_w2c_local = torch.eye(4, device=device)           # identity

    # Slerp-interpolated novel-view cameras (same algorithm as 02_augment.py)
    novel_w2c = generate_novel_view_w2c(
        cam0_w2c_local, cam1_w2c_local, num_matrices=num_novel_views
    ).to(device)   # (N, 4, 4)

    # Randomly assign cam0 or cam1 intrinsics to each novel view
    K_stack  = torch.stack([K[0], K[1]], dim=0)            # (2, 3, 3)
    rand_idx = torch.randint(0, 2, (num_novel_views,), device=device)
    K_novel  = K_stack[rand_idx]                           # (N, 3, 3)

    renders = []
    with torch.no_grad():
        for i in range(num_novel_views):
            try:
                out = gsplat.rasterization(
                    means     = gaussians['means'],
                    quats     = gaussians['quats'],
                    scales    = gaussians['scales'],
                    opacities = gaussians['opacities'],
                    colors    = gaussians['colors'],        # (N, 3) pre-computed RGB
                    viewmats  = novel_w2c[i:i+1].float(),
                    Ks        = K_novel[i:i+1].float(),
                    width     = MAST3R_SIZE,
                    height    = MAST3R_SIZE,
                    sh_degree = None,
                )
                img_np = (out[0][0].detach().cpu().clamp(0, 1).numpy() * 255).astype(np.uint8)
            except Exception as e:
                print(f"    [render error view {i}: {e}] — using blank frame")
                img_np = np.zeros((MAST3R_SIZE, MAST3R_SIZE, 3), dtype=np.uint8)
            renders.append(img_np)

    return (
        renders,
        novel_w2c.cpu().double().numpy(),
        K_novel.cpu().double().numpy(),
        cam0_w2c_local.cpu().double().numpy(),
        cam1_w2c_local.cpu().double().numpy(),
    )


# ── Per-episode processing ────────────────────────────────────────────────────

def load_frame_pair(episode_dir: str, frame_idx: int, cam_ids: list) -> tuple:
    imgs, paths = [], []
    for cam_id in cam_ids:
        p = os.path.join(episode_dir, f'cam{cam_id}', f'{frame_idx:06d}.jpg')
        imgs.append(_get_starster().load_image(p, size=MAST3R_SIZE))
        paths.append(p)
    return imgs, paths


def process_episode(episode_dir: str, splatt3r_model, args) -> bool:
    meta_path = os.path.join(episode_dir, 'meta.json')
    if not os.path.exists(meta_path):
        print(f"  Skipping {episode_dir} — no meta.json")
        return False

    with open(meta_path) as f:
        meta = json.load(f)

    cam_ids   = args.cam_pair
    aug_dir   = os.path.join(episode_dir, 'augmented')
    real_dir  = os.path.join(aug_dir, 'real')
    novel_dir = os.path.join(aug_dir, 'novel')

    if args.skip_done and os.path.exists(os.path.join(aug_dir, 'novel_cameras.npz')):
        print(f"  Skipping {episode_dir} — already done")
        return False

    os.makedirs(real_dir,  exist_ok=True)
    os.makedirs(novel_dir, exist_ok=True)

    n_frames      = meta['n_frames']
    frame_indices = list(range(0, n_frames, args.sample_every))
    print(f"  {n_frames} frames  →  {len(frame_indices)} sampled "
          f"(every {args.sample_every})  |  cam{cam_ids[0]}+cam{cam_ids[1]}  "
          f"|  {args.num_novel_views} novel views each")

    novel_cams = {}
    ep_t = time.time()

    for step, fi in enumerate(frame_indices):
        t0 = time.time()
        print(f"  [{step+1}/{len(frame_indices)}] frame {fi:06d}", end="", flush=True)

        # ── Load images ───────────────────────────────────────────────────────
        imgs, paths = load_frame_pair(episode_dir, fi, cam_ids)

        # Copy real frames
        for cam_id in cam_ids:
            src = os.path.join(episode_dir, f'cam{cam_id}', f'{fi:06d}.jpg')
            dst = os.path.join(real_dir,    f'{fi:06d}_cam{cam_id}.jpg')
            shutil.copy2(src, dst)

        # ── Step 1: Camera poses via Splatt3R's frozen MASt3R encoder ─────────
        tmpdir_obj = tempfile.TemporaryDirectory()
        try:
            scene = _get_starster().reconstruct_scene(
                splatt3r_model.encoder, imgs, paths, args.device,
                tmpdir=tmpdir_obj.name
            )
            w2c = scene.w2c().to(args.device)          # (2, 4, 4)
            K   = scene.intrinsics().to(args.device)   # (2, 3, 3)
        finally:
            tmpdir_obj.cleanup()

        # ── Step 2: Gaussian prediction (single forward pass, no optimisation) ─
        view1 = to_splatt3r_view(imgs[0], args.device, idx=0)
        view2 = to_splatt3r_view(imgs[1], args.device, idx=1)

        with torch.no_grad():
            pred1, pred2 = splatt3r_model(view1, view2)

        gaussians = extract_gaussians(pred1, pred2,
                                      opacity_threshold=args.opacity_threshold,
                                      max_gaussians=args.max_gaussians,
                                      device=args.device)
        del pred1, pred2, view1, view2
        torch.cuda.empty_cache()
        print(f"  {len(gaussians['means'])} Gaussians", end="", flush=True)

        # ── Step 3: Render novel views ────────────────────────────────────────
        renders, novel_w2c_np, K_novel_np, cam0_w2c_np, cam1_w2c_np = \
            render_novel_views(gaussians, w2c[0], w2c[1], K,
                               args.num_novel_views, args.device)

        # ── Save renders ──────────────────────────────────────────────────────
        for k, rgb in enumerate(renders):
            bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
            cv2.imwrite(os.path.join(novel_dir, f'{fi:06d}_novel{k:02d}.jpg'),
                        bgr, [cv2.IMWRITE_JPEG_QUALITY, 95])

        tag = f'{fi:06d}'
        novel_cams[f'{tag}_cam{cam_ids[0]}_w2c'] = cam0_w2c_np   # identity
        novel_cams[f'{tag}_cam{cam_ids[1]}_w2c'] = cam1_w2c_np
        novel_cams[f'{tag}_novel_w2c']            = novel_w2c_np
        novel_cams[f'{tag}_novel_K']              = K_novel_np

        elapsed = time.time() - t0
        done    = step + 1
        eta     = (time.time() - ep_t) / done * (len(frame_indices) - done)
        print(f"  {elapsed:.1f}s/frame  ETA {eta:.0f}s")

    np.savez(os.path.join(aug_dir, 'novel_cameras.npz'), **novel_cams)
    total_novel = len(frame_indices) * args.num_novel_views
    print(f"  Saved {total_novel} novel views + novel_cameras.npz  "
          f"({time.time()-ep_t:.0f}s total)")
    return True


# ── Helpers ───────────────────────────────────────────────────────────────────

def collect_episodes(task_dir: str) -> list:
    return [os.path.join(task_dir, name)
            for name in sorted(os.listdir(task_dir))
            if os.path.isdir(os.path.join(task_dir, name))
            and os.path.exists(os.path.join(task_dir, name, 'meta.json'))]


def parse_args():
    p = argparse.ArgumentParser(
        description='Novel view synthesis with Splatt3R (feed-forward, no GS optimisation)')
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument('--episode_dir', help='Single episode directory')
    src.add_argument('--task_dir',    help='Task directory; processes all episodes')
    p.add_argument('--splatt3r_dir', required=True,
                   help='Path to cloned Splatt3R repo (github.com/btsmart/splatt3r)')
    p.add_argument('--num_novel_views',   type=int, default=6)
    p.add_argument('--sample_every',      type=int, default=15,
                   help='Process every Nth frame (15 ≈ 2 fps from 30 fps)')
    p.add_argument('--opacity_threshold', type=float, default=0.01,
                   help='Prune Gaussians below this opacity (0 = keep all)')
    p.add_argument('--max_gaussians',     type=int,   default=60_000,
                   help='Random-subsample to this many Gaussians before rendering '
                        '(0 = unlimited; lower values reduce GPU memory usage)')
    p.add_argument('--cam_pair',    nargs=2, type=int, default=[0, 1])
    p.add_argument('--skip_done',   action='store_true')
    p.add_argument('--device',      default='cuda')
    return p.parse_args()


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    args = parse_args()

    if args.episode_dir:
        episode_dirs = [args.episode_dir]
    else:
        episode_dirs = collect_episodes(args.task_dir)
        if not episode_dirs:
            print(f"No episodes found under {args.task_dir}")
            return
        print(f"Found {len(episode_dirs)} episode(s) under {args.task_dir}")

    print("\nLoading Splatt3R model (once for all episodes)...")
    splatt3r_model = load_splatt3r(args.splatt3r_dir, args.device)

    total_t = time.time()
    n_done = n_skip = 0

    for i, episode_dir in enumerate(episode_dirs):
        ep_name = (os.path.relpath(episode_dir, args.task_dir)
                   if args.task_dir else episode_dir)
        print(f"\n{'='*60}")
        print(f"Episode {i+1}/{len(episode_dirs)}: {ep_name}")
        print('='*60)
        ok = process_episode(episode_dir, splatt3r_model, args)
        n_done += ok
        n_skip += not ok

    print(f"\nAll done in {time.time()-total_t:.0f}s  "
          f"({n_done} processed, {n_skip} skipped)")
    print("\nNext: python 03_segment.py "
          + (f"--task_dir {args.task_dir}" if args.task_dir
             else f"--episode_dir {args.episode_dir}"))


if __name__ == '__main__':
    main()
