# -*- coding: utf-8 -*-
"""Grounded-SAM2-Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyJ2F0AK3-_n5_kc6Ok-KownLlSqpV5-
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/IDEA-Research/Grounded-SAM-2
# %cd Grounded-SAM-2

# Cell 2: Install PyTorch (Colab usually already has this, but ensure correct version)
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# Cell 3: Set CUDA_HOME (critical for Grounding DINO compilation)
import os
os.environ["CUDA_HOME"] = "/usr/local/cuda"

# Install SAM 2
!pip install -e . -q

# Install Grounding DINO (this compiles the CUDA op — takes ~3-5 min)
!pip install --no-build-isolation -e grounding_dino -q

# Cell 4: Download model checkpoints
!cd checkpoints && bash download_ckpts.sh
!cd gdino_checkpoints && bash download_ckpts.sh

!pip install supervision -q

# Cell 5: Run the HuggingFace demo (easiest)
!python grounded_sam2_hf_model_demo.py

import os
import cv2
import torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.colors import to_rgba
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor



SAM2_CHECKPOINT  = "./checkpoints/sam2.1_hiera_large.pt"
SAM2_MODEL_CFG   = "configs/sam2.1/sam2.1_hiera_l.yaml"
GDINO_MODEL_ID   = "IDEA-Research/grounding-dino-tiny"
DEVICE           = "cuda" if torch.cuda.is_available() else "cpu"
BOX_THRESHOLD    = 0.35
TEXT_THRESHOLD   = 0.25

# ── Load models ───────────────────────────────────────────────────────────────
print("Loading Grounding DINO...")
processor = AutoProcessor.from_pretrained(GDINO_MODEL_ID)
gdino     = AutoModelForZeroShotObjectDetection.from_pretrained(GDINO_MODEL_ID).to(DEVICE)

print("Loading SAM 2...")
sam2       = build_sam2(SAM2_MODEL_CFG, SAM2_CHECKPOINT, device=DEVICE)
predictor  = SAM2ImagePredictor(sam2)

# ── CONFIG ── change these two lines ──────────────────────────────────────────
IMAGE_PATH  = "/content/Easy-Balanced-Lunch-Plate-.jpg"   # path to your image
TEXT_PROMPT = "carrots."          # dot-separated labels
# ──────────────────────────────────────────────────────────────────────────────

# ── Run inference ─────────────────────────────────────────────────────────────
image_pil = Image.open(IMAGE_PATH).convert("RGB")
image_np  = np.array(image_pil)

# Step 1: Grounding DINO → boxes
inputs  = processor(images=image_pil, text=TEXT_PROMPT, return_tensors="pt").to(DEVICE)
with torch.no_grad():
    outputs = gdino(**inputs)

results = processor.post_process_grounded_object_detection(
    outputs,
    inputs.input_ids,
    threshold=BOX_THRESHOLD,          # was box_threshold
    text_threshold=TEXT_THRESHOLD,
    target_sizes=[image_pil.size[::-1]]
)[0]

boxes  = results["boxes"].cpu().numpy()   # (N, 4) xyxy
labels = results["labels"]
scores = results["scores"].cpu().numpy()

print(f"Detected {len(boxes)} object(s): {labels}")

# Step 2: SAM 2 → masks
predictor.set_image(image_np)
if len(boxes) > 0:
    masks, _, _ = predictor.predict(
        point_coords=None,
        point_labels=None,
        box=boxes,
        multimask_output=False,
    )
    # masks shape: (N, 1, H, W) → squeeze to (N, H, W)
    if masks.ndim == 4:
        masks = masks.squeeze(1)
else:
    masks = []

# ── Visualize ─────────────────────────────────────────────────────────────────
COLORS = plt.cm.get_cmap("tab10").colors   # 10 distinct colors

fig, ax = plt.subplots(1, 1, figsize=(12, 8))
ax.imshow(image_np)

for i, (mask, label, score, box) in enumerate(zip(masks, labels, scores, boxes)):
    color = COLORS[i % len(COLORS)]

    # Overlay mask
    colored_mask = np.zeros((*mask.shape, 4), dtype=np.float32)
    colored_mask[mask > 0] = [*color[:3], 0.65]
    ax.imshow(colored_mask)

    # Bounding box
    x1, y1, x2, y2 = box
    rect = patches.Rectangle(
        (x1, y1), x2 - x1, y2 - y1,
        linewidth=2, edgecolor=color, facecolor="none"
    )
    ax.add_patch(rect)

    # Label + score
    ax.text(
        x1, y1 - 5, f"{label} {score:.2f}",
        color="white", fontsize=10, fontweight="bold",
        bbox=dict(facecolor=color, alpha=0.7, pad=2, edgecolor="none")
    )

    # Center of mass
    ys, xs = np.where(mask > 0)
    if len(xs) > 0:
        cx, cy = xs.mean(), ys.mean()
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=2.5, color="white")
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=1, color=color)

ax.axis("off")
ax.set_title(f"Prompt: \"{TEXT_PROMPT}\"", fontsize=13)
plt.tight_layout()
plt.savefig("segmentation_result.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved → segmentation_result.png")

# ── CONFIG ── change these two lines ──────────────────────────────────────────
IMAGE_PATH  = "/content/kinova_jaco_image9.jpg"   # path to your image
TEXT_PROMPT = "robotic arm."          # dot-separated labels
# ──────────────────────────────────────────────────────────────────────────────

# ── Run inference ─────────────────────────────────────────────────────────────
image_pil = Image.open(IMAGE_PATH).convert("RGB")
image_np  = np.array(image_pil)

# Step 1: Grounding DINO → boxes
inputs  = processor(images=image_pil, text=TEXT_PROMPT, return_tensors="pt").to(DEVICE)
with torch.no_grad():
    outputs = gdino(**inputs)

results = processor.post_process_grounded_object_detection(
    outputs,
    inputs.input_ids,
    threshold=BOX_THRESHOLD,          # was box_threshold
    text_threshold=TEXT_THRESHOLD,
    target_sizes=[image_pil.size[::-1]]
)[0]

boxes  = results["boxes"].cpu().numpy()   # (N, 4) xyxy
labels = results["labels"]
scores = results["scores"].cpu().numpy()

print(f"Detected {len(boxes)} object(s): {labels}")

# Step 2: SAM 2 → masks
predictor.set_image(image_np)
if len(boxes) > 0:
    masks, _, _ = predictor.predict(
        point_coords=None,
        point_labels=None,
        box=boxes,
        multimask_output=False,
    )
    # masks shape: (N, 1, H, W) → squeeze to (N, H, W)
    if masks.ndim == 4:
        masks = masks.squeeze(1)
else:
    masks = []

# ── Visualize ─────────────────────────────────────────────────────────────────
COLORS = plt.cm.get_cmap("tab10").colors   # 10 distinct colors

fig, ax = plt.subplots(1, 1, figsize=(12, 8))
ax.imshow(image_np)

for i, (mask, label, score, box) in enumerate(zip(masks, labels, scores, boxes)):
    color = COLORS[i % len(COLORS)]

    # Overlay mask
    colored_mask = np.zeros((*mask.shape, 4), dtype=np.float32)
    colored_mask[mask > 0] = [*color[:3], 0.65]
    ax.imshow(colored_mask)

    # Bounding box
    x1, y1, x2, y2 = box
    rect = patches.Rectangle(
        (x1, y1), x2 - x1, y2 - y1,
        linewidth=2, edgecolor=color, facecolor="none"
    )
    ax.add_patch(rect)

    # Label + score
    ax.text(
        x1, y1 - 5, f"{label} {score:.2f}",
        color="white", fontsize=10, fontweight="bold",
        bbox=dict(facecolor=color, alpha=0.7, pad=2, edgecolor="none")
    )

    # Center of mass
    ys, xs = np.where(mask > 0)
    if len(xs) > 0:
        cx, cy = xs.mean(), ys.mean()
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=2.5, color="white")
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=1, color=color)

ax.axis("off")
ax.set_title(f"Prompt: \"{TEXT_PROMPT}\"", fontsize=13)
plt.tight_layout()
plt.savefig("segmentation_result.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved → segmentation_result.png")

# ── CONFIG ── change these two lines ──────────────────────────────────────────
IMAGE_PATH  = "/content/plate-showing-balanced-meal-different-600nw-2722426991.webp"   # path to your image
TEXT_PROMPT = "fish. rice. tomato. "          # dot-separated labels
# ──────────────────────────────────────────────────────────────────────────────

# ── Run inference ─────────────────────────────────────────────────────────────
image_pil = Image.open(IMAGE_PATH).convert("RGB")
image_np  = np.array(image_pil)

# Step 1: Grounding DINO → boxes
inputs  = processor(images=image_pil, text=TEXT_PROMPT, return_tensors="pt").to(DEVICE)
with torch.no_grad():
    outputs = gdino(**inputs)

results = processor.post_process_grounded_object_detection(
    outputs,
    inputs.input_ids,
    threshold=BOX_THRESHOLD,          # was box_threshold
    text_threshold=TEXT_THRESHOLD,
    target_sizes=[image_pil.size[::-1]]
)[0]

boxes  = results["boxes"].cpu().numpy()   # (N, 4) xyxy
labels = results["labels"]
scores = results["scores"].cpu().numpy()

print(f"Detected {len(boxes)} object(s): {labels}")

# Step 2: SAM 2 → masks
predictor.set_image(image_np)
if len(boxes) > 0:
    masks, _, _ = predictor.predict(
        point_coords=None,
        point_labels=None,
        box=boxes,
        multimask_output=False,
    )
    # masks shape: (N, 1, H, W) → squeeze to (N, H, W)
    if masks.ndim == 4:
        masks = masks.squeeze(1)
else:
    masks = []

# ── Visualize ─────────────────────────────────────────────────────────────────
COLORS = plt.cm.get_cmap("tab10").colors   # 10 distinct colors

fig, ax = plt.subplots(1, 1, figsize=(12, 8))
ax.imshow(image_np)

for i, (mask, label, score, box) in enumerate(zip(masks, labels, scores, boxes)):
    color = COLORS[i % len(COLORS)]

    # Overlay mask
    colored_mask = np.zeros((*mask.shape, 4), dtype=np.float32)
    colored_mask[mask > 0] = [*color[:3], 0.65]
    ax.imshow(colored_mask)

    # Bounding box
    x1, y1, x2, y2 = box
    rect = patches.Rectangle(
        (x1, y1), x2 - x1, y2 - y1,
        linewidth=2, edgecolor=color, facecolor="none"
    )
    ax.add_patch(rect)

    # Label + score
    ax.text(
        x1, y1 - 5, f"{label} {score:.2f}",
        color="white", fontsize=10, fontweight="bold",
        bbox=dict(facecolor=color, alpha=0.7, pad=2, edgecolor="none")
    )

    # Center of mass
    ys, xs = np.where(mask > 0)
    if len(xs) > 0:
        cx, cy = xs.mean(), ys.mean()
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=2.5, color="white")
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=1, color=color)

ax.axis("off")
ax.set_title(f"Prompt: \"{TEXT_PROMPT}\"", fontsize=13)
plt.tight_layout()
plt.savefig("segmentation_result.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved → segmentation_result.png")

# ── CONFIG ── change these two lines ──────────────────────────────────────────
IMAGE_PATH  = "/content/Screenshot 2026-05-04 at 10.01.53 PM.png"   # path to your image
TEXT_PROMPT = "robot arm."          # dot-separated labels
# ──────────────────────────────────────────────────────────────────────────────

# ── Run inference ─────────────────────────────────────────────────────────────
image_pil = Image.open(IMAGE_PATH).convert("RGB")
image_np  = np.array(image_pil)

# Step 1: Grounding DINO → boxes
inputs  = processor(images=image_pil, text=TEXT_PROMPT, return_tensors="pt").to(DEVICE)
with torch.no_grad():
    outputs = gdino(**inputs)

results = processor.post_process_grounded_object_detection(
    outputs,
    inputs.input_ids,
    threshold=BOX_THRESHOLD,          # was box_threshold
    text_threshold=TEXT_THRESHOLD,
    target_sizes=[image_pil.size[::-1]]
)[0]

boxes  = results["boxes"].cpu().numpy()   # (N, 4) xyxy
labels = results["labels"]
scores = results["scores"].cpu().numpy()

print(f"Detected {len(boxes)} object(s): {labels}")

# Step 2: SAM 2 → masks
predictor.set_image(image_np)
if len(boxes) > 0:
    masks, _, _ = predictor.predict(
        point_coords=None,
        point_labels=None,
        box=boxes,
        multimask_output=False,
    )
    # masks shape: (N, 1, H, W) → squeeze to (N, H, W)
    if masks.ndim == 4:
        masks = masks.squeeze(1)
else:
    masks = []

# ── Visualize ─────────────────────────────────────────────────────────────────
COLORS = plt.cm.get_cmap("tab10").colors   # 10 distinct colors

fig, ax = plt.subplots(1, 1, figsize=(12, 8))
ax.imshow(image_np)

for i, (mask, label, score, box) in enumerate(zip(masks, labels, scores, boxes)):
    color = COLORS[i % len(COLORS)]

    # Overlay mask
    colored_mask = np.zeros((*mask.shape, 4), dtype=np.float32)
    colored_mask[mask > 0] = [*color[:3], 0.65]
    ax.imshow(colored_mask)

    # Bounding box
    x1, y1, x2, y2 = box
    rect = patches.Rectangle(
        (x1, y1), x2 - x1, y2 - y1,
        linewidth=2, edgecolor=color, facecolor="none"
    )
    ax.add_patch(rect)

    # Label + score
    ax.text(
        x1, y1 - 5, f"{label} {score:.2f}",
        color="white", fontsize=10, fontweight="bold",
        bbox=dict(facecolor=color, alpha=0.7, pad=2, edgecolor="none")
    )

    # Center of mass
    ys, xs = np.where(mask > 0)
    if len(xs) > 0:
        cx, cy = xs.mean(), ys.mean()
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=2.5, color="white")
        ax.plot(cx, cy, marker="+", markersize=15, markeredgewidth=1, color=color)

ax.axis("off")
ax.set_title(f"Prompt: \"{TEXT_PROMPT}\"", fontsize=13)
plt.tight_layout()
plt.savefig("segmentation_result.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved → segmentation_result.png")